update keywords stats
rubik09/botStats pull request #32
Opened 2024-04-25 18:24 UTC by yurakozyrenko

2024-04-25 19:14 UTC, rubik09 requested changes

2024-04-25 19:14 UTC, rubik09 commented on src/stats/stats.service.ts
> +    const keywordIncludes = await this.keywordsService.findOneKeywordInMsg(message, id);
нейминг плохій переменной

2024-04-25 19:14 UTC, rubik09 commented on src/keywords/keywords.service.ts
> +  async findOneKeywordInMsg(message: string, id: UserSession['id']): Promise<Keyword> {
нейминг плохой

2024-04-25 19:14 UTC, rubik09 commented on src/keywords/keywords.repository.ts
> +  async findOneKeywordInMsg(message: string, userSessionId: number): Promise<Keyword> {
нейминг

2024-04-26 10:50 UTC, DenisLokhtin approved these changes

2024-04-26 16:57 UTC, rubik09 approved these changes

2024-04-26 16:57 UTC, merged