delete all google sheets logic, replaced with createCalculatedStats
rubik09/botStats pull request #34
Opened 2024-04-29 06:07 UTC by DenisLokhtin

2024-04-29 06:37 UTC, yurakozyrenko approved these changes

2024-04-29 14:31 UTC, rubik09 commented on env.template
> +CRON_TIME_NIGHT='0 10 * * *'
Нестыковка ,ночь в 10 утра ?)

2024-04-30 06:49 UTC, rubik09 requested changes

2024-04-30 06:49 UTC, rubik09 commented on src/stats/stats.service.ts
>        const { apiId, id } = account;
Это можно сразу в месте где for делать

2024-04-30 07:30 UTC, rubik09 approved these changes

2024-04-30 07:31 UTC, merged