add logic to dynamic cron scheduler
rubik09/botStats pull request #44
Opened 2024-05-23 08:03 UTC by DenisLokhtin

2024-05-23 08:45 UTC, yurakozyrenko approved these changes

2024-05-27 09:15 UTC, rubik09 requested changes

2024-05-27 09:15 UTC, rubik09 commented on src/cron/dto/cron.dto.ts
> +  id: CronEntity['id'];
это откуда??

2024-05-27 09:15 UTC, rubik09 commented on src/cron/cron.controller.ts
> +  async updateCronJob(@Param('id') id: Keyword['id'], @Body() updateCronJobDto: UpdateCronJobDto) {
верный тип??

2024-05-27 09:15 UTC, rubik09 commented on src/cron/cron.controller.ts
> +  async deleteCronJob(@Param('id') id: PersonalInfo['id']) {
верный тип?

2024-05-27 10:59 UTC, rubik09 requested changes

2024-05-27 10:59 UTC, rubik09 commented on src/cron/entity/cron.entity.ts
> +export class CronEntity {
по неймингу беда

2024-05-27 11:02 UTC, merged