updat TelegramClient
rubik09/botStats pull request #49
Opened 2024-06-12 08:24 UTC by yurakozyrenko

2024-06-14 07:30 UTC, DenisLokhtin approved these changes

2024-06-18 08:29 UTC, rubik09 requested changes

2024-06-18 08:29 UTC, rubik09 commented on src/utils/consts.ts
> +  logChatId: '-4128642967',
какого фига айди канала в общем доступе???

2024-06-18 08:29 UTC, rubik09 commented on src/utils/consts.ts
> +  maxRetries: 5,
что за magic число?
константы

2024-06-19 08:42 UTC, closed without merging