Update telegram client
rubik09/botStats pull request #52
Opened 2024-06-21 12:44 UTC by yurakozyrenko

2024-06-24 06:22 UTC, DenisLokhtin approved these changes

2024-06-24 07:59 UTC, rubik09 requested changes

2024-06-24 07:59 UTC, rubik09 commented on src/botAlert/botAlert.provider.ts
> +  private readonly telegramBotApiUrl = 'https://api.telegram.org/bot';
В константы вынести

2024-06-24 07:59 UTC, rubik09 commented on src/botAlert/botAlert.provider.ts
> +    const data = {
Интерфейс сделать

2024-06-24 07:59 UTC, rubik09 commented on src/botAlert/botAlert.provider.ts
> +    await firstValueFrom(this.httpClient.post(`${this.telegramBotApiUrl}${this.botToken}/sendMessage`, data));
Урл выше сформировать

2024-06-25 05:32 UTC, rubik09 requested changes

2024-06-25 05:32 UTC, rubik09 commented on src/telegramConnect/telegramConnect.service.ts
> +const { CHAT_ID_ALERT } = config();
????
Это откуда такой импорт env переменнноц??

2024-06-25 05:32 UTC, rubik09 commented on src/userSession/userSession.service.ts
> +const { CHAT_ID_ALERT } = config();
??????

2024-06-25 05:32 UTC, rubik09 commented on src/userSession/userSession.service.ts
> +    const results = await telegramAccountsInit(allSessions);
Не, обычный цикл 
В нем если кто-то не смог 
Алерт и дальше по цепочке идем

2024-06-25 05:32 UTC, rubik09 commented on src/utils/createClient.ts
> +      connectionRetries: createCLientConfig.CONNECTION_RETRIES,
Зачем так каждую переменную передавать ?
Если можно целый объект передать со всеми параметрами

2024-06-25 05:32 UTC, rubik09 commented on src/utils/telegramInit.ts
> +async function telegramAccountsInit(allSessions: UserSession[]): Promise<PromiseSettledResult<void>[]> {
Тоже самое что выше писал 
Тут за скоростью не гонимся

2024-06-26 05:52 UTC, rubik09 requested changes

2024-07-01 05:22 UTC, rubik09 approved these changes

2024-07-01 05:23 UTC, merged